// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8D8TIsjjxepWd5uKxKmUVzB3hRxjLQVU',
    appId: '1:161784183903:web:7f2e5515dc07849a0f2fea',
    messagingSenderId: '161784183903',
    projectId: 'bridgestonetyrematch',
    authDomain: 'bridgestonetyrematch.firebaseapp.com',
    storageBucket: 'bridgestonetyrematch.appspot.com',
    measurementId: 'G-4EZLK38RPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx8PcQF__wtduKmvhs33nQNOhw9J0Oi5E',
    appId: '1:161784183903:android:0507f8a9f38aba220f2fea',
    messagingSenderId: '161784183903',
    projectId: 'bridgestonetyrematch',
    storageBucket: 'bridgestonetyrematch.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfNBZ_lDG8e5XYbFzoWREv2oUneGC0U94',
    appId: '1:161784183903:ios:9ec3f4eef35e74c40f2fea',
    messagingSenderId: '161784183903',
    projectId: 'bridgestonetyrematch',
    storageBucket: 'bridgestonetyrematch.appspot.com',
    iosClientId: '161784183903-507enl347rrvk5ij8l3vocm8nsqmpdv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.bridgeStoneTyreMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfNBZ_lDG8e5XYbFzoWREv2oUneGC0U94',
    appId: '1:161784183903:ios:9ec3f4eef35e74c40f2fea',
    messagingSenderId: '161784183903',
    projectId: 'bridgestonetyrematch',
    storageBucket: 'bridgestonetyrematch.appspot.com',
    iosClientId: '161784183903-507enl347rrvk5ij8l3vocm8nsqmpdv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.bridgeStoneTyreMatch',
  );
}
